// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUEDMoqTtJttijKjKUlgRvsb9jJUmOWTw',
    appId: '1:182615455279:web:c4dfad8d7bdec9dc9138da',
    messagingSenderId: '182615455279',
    projectId: 'first-app-3e0cd',
    authDomain: 'first-app-3e0cd.firebaseapp.com',
    storageBucket: 'first-app-3e0cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5zjpi4sd4Cr4kVRhZu0qVSkZs6UOeEM',
    appId: '1:182615455279:android:1f1fc3b1ff5e9e919138da',
    messagingSenderId: '182615455279',
    projectId: 'first-app-3e0cd',
    storageBucket: 'first-app-3e0cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsI7zy2TaN_hLn8Rt76dvKHx__VafQtyM',
    appId: '1:182615455279:ios:83749ca77379076c9138da',
    messagingSenderId: '182615455279',
    projectId: 'first-app-3e0cd',
    storageBucket: 'first-app-3e0cd.firebasestorage.app',
    iosBundleId: 'com.example.reel1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsI7zy2TaN_hLn8Rt76dvKHx__VafQtyM',
    appId: '1:182615455279:ios:83749ca77379076c9138da',
    messagingSenderId: '182615455279',
    projectId: 'first-app-3e0cd',
    storageBucket: 'first-app-3e0cd.firebasestorage.app',
    iosBundleId: 'com.example.reel1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUEDMoqTtJttijKjKUlgRvsb9jJUmOWTw',
    appId: '1:182615455279:web:29a81057de29a6cd9138da',
    messagingSenderId: '182615455279',
    projectId: 'first-app-3e0cd',
    authDomain: 'first-app-3e0cd.firebaseapp.com',
    storageBucket: 'first-app-3e0cd.firebasestorage.app',
  );
}
